debug image status

diff --git a/.github/workflows/mlops-pipeline.yml b/.github/workflows/mlops-pipeline.yml
--- a/.github/workflows/mlops-pipeline.yml
+++ b/.github/workflows/mlops-pipeline.yml
@@ -147,10 +147,10 @@ jobs:
           curl -f http://localhost:8000/health && break || sleep 5;
         done
         docker logs test-api
-    - name: Clean up Test Container
-      run: |
-        docker stop test-api || true
-        docker rm test-api || true
+    # - name: Clean up Test Container
+    #   run: |
+    #     docker stop test-api || true
+    #     docker rm test-api || true
       
     - name: Log in to GitHub Container Registry
       uses: docker/login-action@v2
